package com.aditya.olap_performance.domain;

import java.io.Serializable;


public record Train(
        String id,
        Long msSubClass,
        String msZoning,
        Double lotFrontage, // Nullable(Float64)
        Long lotArea,
        String street,
        String alley, // Nullable(String)
        String lotShape,
        String landContour,
        String utilities,
        String lotConfig,
        String landSlope,
        String neighborhood,
        String condition1,
        String condition2,
        String bldgType,
        String houseStyle,
        Long overallQual,
        Long overallCond,
        Long yearBuilt,
        Long yearRemodAdd,
        String roofStyle,
        String roofMatl,
        String exterior1st,
        String exterior2nd,
        String masVnrType,
        Double masVnrArea,
        String exterQual,
        String exterCond,
        String foundation,
        String bsmtQual,
        String bsmtCond,
        String bsmtExposure,
        String bsmtFinType1,
        Long bsmtFinSF1,
        String bsmtFinType2,
        Long bsmtFinSF2,
        Long bsmtUnfSF,
        Long totalBsmtSF,
        String heating,
        String heatingQC,
        String centralAir,
        String electrical,
        Long firstFlrSF, // Mapped from 1stFlrSF
        Long secondFlrSF, // Mapped from 2ndFlrSF
        Long lowQualFinSF,
        Long grLivArea,
        Long bsmtFullBath,
        Long bsmtHalfBath,
        Long fullBath,
        Long halfBath,
        Long bedroomAbvGr,
        Long kitchenAbvGr,
        String kitchenQual,
        Long totRmsAbvGrd,
        String functional,
        Long fireplaces,
        String fireplaceQu,
        String garageType,
        Double garageYrBlt,
        String garageFinish,
        Long garageCars,
        Long garageArea,
        String garageQual,
        String garageCond,
        String pavedDrive,
        Long woodDeckSF,
        Long openPorchSF,
        Long enclosedPorch,
        Long threeSsnPorch, // Mapped from 3SsnPorch
        Long screenPorch,
        Long poolArea,
        String poolQC,
        String fence,
        String miscFeature,
        Long miscVal,
        Long moSold,
        Long yrSold,
        String saleType,
        String saleCondition,
        Long salePrice
) implements Serializable {}